kind: pipeline
type: docker
name: build_image

platform:
  os: linux
  arch: arm64

steps:
  - name: Get git commit tag
    image: alpine
    commands:
      - apk add git
      - git rev-parse --short HEAD > .tags
      - cat .tags
  - name: Build and push
    image: plugins/docker
    settings:
      registry: git.odzi.dog
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
      repo: git.odzi.dog/omnidoc/web

---
kind: pipeline
type: docker
name: deploy_production

platform:
  os: linux
  arch: arm64

steps:
  - name: Trigger internal/docs.odzi.dog pipeline
    image: plugins/downstream
    settings:
      server: https://drone.odzi.dog
      token:
        from_secret: DRONE_TOKEN
      fork: true
      repositories:
        - internal/docs.odzi.dog

depends_on:
  - build_image
